name: "Set Up"
description: "Set up workflow"
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      shell: bash

    - name: Extract google-services.json
      run: |
        cat << EOF > ./composeApp/google-services.json
        ${{ secrets.GOOGLE_SERVICES }}
        EOF
      shell: bash
