// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'overview_response.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

OverviewResponse _$OverviewResponseFromJson(Map<String, dynamic> json) =>
    OverviewResponse(
      json['AssetType'] as String? ?? '',
      json['Description'] as String? ?? '',
      json['CIK'] as String? ?? '',
      json['Exchange'] as String? ?? '',
      json['Currency'] as String? ?? '',
      json['Country'] as String? ?? '',
      json['sector'] as String? ?? '',
      json['Industry'] as String? ?? '',
      json['Address'] as String? ?? '',
      json['FiscalYearEnd'] as String? ?? '',
      json['LatestQuarter'] as String? ?? '',
      json['MarketCapitalization'] as String? ?? '',
      json['EBITDA'] as String? ?? '',
      json['PERatio'] as String? ?? '',
      json['PEGRatio'] as String? ?? '',
      json['BookValue'] as String? ?? '',
      json['DividendPerShare'] as String? ?? '',
      json['DividendYield'] as String? ?? '',
      json['EPS'] as String? ?? '',
      json['RevenuePerShareTTM'] as String? ?? '',
      json['ProfitMargin'] as String? ?? '',
      json['OperatingMarginTTM'] as String? ?? '',
      json['ReturnOnAssetsTTM'] as String? ?? '',
      json['ReturnOnEquityTTM'] as String? ?? '',
      json['RevenueTTM'] as String? ?? '',
      json['GrossProfitTTM'] as String? ?? '',
      json['DilutedEPSTTM'] as String? ?? '',
      json['QuarterlyEarningsGrowthYOY'] as String? ?? '',
      json['QuarterlyRevenueGrowthYOY'] as String? ?? '',
      json['AnalystTargetPrice'] as String? ?? '',
      json['TrailingPE'] as String? ?? '',
      json['ForwardPE'] as String? ?? '',
      json['PriceToSalesRatioTTM'] as String? ?? '',
      json['PriceToBookRatio'] as String? ?? '',
      json['EVToRevenue'] as String? ?? '',
      json['EVToEBITDA'] as String? ?? '',
      json['Beta'] as String? ?? '',
      json['52WeekHigh'] as String? ?? '',
      json['52WeekLow'] as String? ?? '',
      json['50DayMovingAverage'] as String? ?? '',
      json['200DayMovingAverage'] as String? ?? '',
      json['SharesOutstanding'] as String? ?? '',
      json['DividendDate'] as String? ?? '',
      json['ExDividendDate'] as String? ?? '',
      json['Symbol'] as String? ?? '',
      json['Name'] as String? ?? '',
    );

Map<String, dynamic> _$OverviewResponseToJson(OverviewResponse instance) =>
    <String, dynamic>{
      'Symbol': instance.symbol,
      'AssetType': instance.assetType,
      'Name': instance.name,
      'Description': instance.description,
      'CIK': instance.cik,
      'Exchange': instance.exchange,
      'Currency': instance.currency,
      'Country': instance.country,
      'sector': instance.sector,
      'Industry': instance.industry,
      'Address': instance.address,
      'FiscalYearEnd': instance.fiscalYearEnd,
      'LatestQuarter': instance.latestQuarter,
      'MarketCapitalization': instance.marketCapitalization,
      'EBITDA': instance.ebitda,
      'PERatio': instance.peRatio,
      'PEGRatio': instance.pegRatio,
      'BookValue': instance.bookValue,
      'DividendPerShare': instance.dividendPerShare,
      'DividendYield': instance.dividendYield,
      'EPS': instance.eps,
      'RevenuePerShareTTM': instance.revenuePerShareTtm,
      'ProfitMargin': instance.profitMargin,
      'OperatingMarginTTM': instance.operatingMarginTtm,
      'ReturnOnAssetsTTM': instance.returnOnAssetsTtm,
      'ReturnOnEquityTTM': instance.returnOnEquityTtm,
      'RevenueTTM': instance.revenueTtm,
      'GrossProfitTTM': instance.grossProfitTtm,
      'DilutedEPSTTM': instance.dilutedEpsTtm,
      'QuarterlyEarningsGrowthYOY': instance.quarterlyEarningsGrowthYoy,
      'QuarterlyRevenueGrowthYOY': instance.quarterlyRevenueGrowthYoy,
      'AnalystTargetPrice': instance.analystTargetPrice,
      'TrailingPE': instance.trailingPe,
      'ForwardPE': instance.forwardPe,
      'PriceToSalesRatioTTM': instance.priceToSalesRatioTtm,
      'PriceToBookRatio': instance.priceToBookRatio,
      'EVToRevenue': instance.evToRevenue,
      'EVToEBITDA': instance.evToEbitda,
      'Beta': instance.beta,
      '52WeekHigh': instance.high52Week,
      '52WeekLow': instance.low52Week,
      '50DayMovingAverage': instance.movingAverage50Day,
      '200DayMovingAverage': instance.movingAverage200Day,
      'SharesOutstanding': instance.sharesOutstanding,
      'DividendDate': instance.dividendDate,
      'ExDividendDate': instance.exDividendDate,
    };
