// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz6jJxD5I8j2ktKWaU_6irJEnd4Dlk4sM',
    appId: '1:919173750264:web:d3662e7563701326bc0a0d',
    messagingSenderId: '919173750264',
    projectId: 'capital-gain-calculator-b48d8',
    authDomain: 'capital-gain-calculator-b48d8.firebaseapp.com',
    storageBucket: 'capital-gain-calculator-b48d8.appspot.com',
    measurementId: 'G-RRDRSGW1QK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoXdtFxLp2ffgrM36hd3SsQAsBRfWY6tU',
    appId: '1:919173750264:android:e755181ff9634274bc0a0d',
    messagingSenderId: '919173750264',
    projectId: 'capital-gain-calculator-b48d8',
    storageBucket: 'capital-gain-calculator-b48d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASd07ccbAmX80FcBbOAE304IfTQjCTkmo',
    appId: '1:919173750264:ios:58c722603679f5b8bc0a0d',
    messagingSenderId: '919173750264',
    projectId: 'capital-gain-calculator-b48d8',
    storageBucket: 'capital-gain-calculator-b48d8.appspot.com',
    iosClientId: '919173750264-t7kenr3r4gd5tpan6pdnol2gm0v3mbt0.apps.googleusercontent.com',
    iosBundleId: 'com.example.capitalGainCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASd07ccbAmX80FcBbOAE304IfTQjCTkmo',
    appId: '1:919173750264:ios:58c722603679f5b8bc0a0d',
    messagingSenderId: '919173750264',
    projectId: 'capital-gain-calculator-b48d8',
    storageBucket: 'capital-gain-calculator-b48d8.appspot.com',
    iosClientId: '919173750264-t7kenr3r4gd5tpan6pdnol2gm0v3mbt0.apps.googleusercontent.com',
    iosBundleId: 'com.example.capitalGainCalculator',
  );
}
