name: portfolio_api
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  all_portfolios:
    path: ../all_portfolios
  common:
    path: ../../../common
  portfolio_create:
    path: ../portfolio_create
  portfolio_details:
    path: ../portfolio_details
  portfolio_use_case:
    path: ../portfolio_use_case

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

