name: all_portfolios
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.16.0
  flutter_bloc: ^8.1.1
  flutter:
    sdk: flutter
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0

  common:
    path: ../../../common
  physical_currency:
    path: ../../../physical_currency
  navigation:
    path: ../../../navigation
  portfolio_data:
    path: ../portfolio_data
  portfolio_use_case:
    path: ../portfolio_use_case

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:  ^2.2.0

flutter:
