name: KMP CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Up
        uses: ./.github/actions/setup
        with:
          secrets_google_services:  ${{ secrets.GOOGLE_SERVICES }}

      - name: Build with Gradle
        run: ./gradlew :composeApp:assembleDebug

  tests:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Up
        uses: ./.github/actions/setup
        with:
          secrets_google_services: ${{ secrets.GOOGLE_SERVICES }}

      - name: Run unit tests
        run: ./gradlew --continue clean test

      - name: Summarize tests results
        uses: jeantessier/test-summary-action@v1
        if: ${{ always() }}

  ktlint:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Up
        uses: ./.github/actions/setup
        with:
          secrets_google_services: ${{ secrets.GOOGLE_SERVICES }}

      - name: Run ktlint
        run: ./gradlew --continue clean ktlintCheck

  kover:
    needs: [tests, ktlint]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Up
        uses: ./.github/actions/setup
        with:
          secrets_google_services: ${{ secrets.GOOGLE_SERVICES }}

      - name: Run kover
        run: ./gradlew clean composeApp:koverHtmlReportDebug
