name: KMP CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Up
        uses: ./.github/actions/setup
        with:
          secrets_google_services:  ${{ secrets.GOOGLE_SERVICES }}

      - name: Build with Gradle
        run: ./gradlew :composeApp:assembleDebug

  tests:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Up
        uses: ./.github/actions/setup
        with:
          secrets_google_services: ${{ secrets.GOOGLE_SERVICES }}

      - name: Run unit tests
        run: ./gradlew --continue clean testDebug

      - name: Summarize tests results
        uses: jeantessier/test-summary-action@v1
        if: ${{ always() }}

  ktlint:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Up
        uses: ./.github/actions/setup
        with:
          secrets_google_services: ${{ secrets.GOOGLE_SERVICES }}

      - name: Run ktlint
        run: ./gradlew --continue clean ktlintCheck

  kover:
    needs: [tests, ktlint]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Up
        uses: ./.github/actions/setup
        with:
          secrets_google_services: ${{ secrets.GOOGLE_SERVICES }}

      - name: Run kover
        run: ./gradlew clean composeApp:koverXmlReportDebug

      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils

      - name: Parse kover report line values
        id: kover-line-values
        uses: ./.github/actions/kover
        with:
         path: "composeApp/build/reports/kover/reportDebug.xml"
         type: "LINE"

      - name: Parse kover report class values
        id: kover-class-values
        uses: ./.github/actions/kover
        with:
          path: "composeApp/build/reports/kover/reportDebug.xml"
          type: "CLASS"

      - name: Parse kover report instruction values
        id: kover-instruction-values
        uses: ./.github/actions/kover
        with:
          path: "composeApp/build/reports/kover/reportDebug.xml"
          type: "INSTRUCTION"

      - name: Parse kover report branch values
        id: kover-branch-values
        uses: ./.github/actions/kover
        with:
          path: "composeApp/build/reports/kover/reportDebug.xml"
          type: "BRANCH"

      - name: Parse kover report method values
        id: kover-method-values
        uses: ./.github/actions/kover
        with:
          path: "composeApp/build/reports/kover/reportDebug.xml"
          type: "METHOD"

      - name: Kover summary
        uses: jazanne/job-summary-action@v1
        with:
          summary: |
            | Type | Covered | Missed | Percent |
            |------|:-------:|:------:|:-------:|
            | Instruction | ${{ steps.kover-instruction-values.outputs.covered }} | ${{ steps.kover-instruction-values.outputs.missed }} | ![](https://progress-bar.xyz/${{ steps.kover-instruction-values.outputs.percent }}) |
            | Branch | ${{ steps.kover-branch-values.outputs.covered }} | ${{ steps.kover-branch-values.outputs.missed }} | ![](https://progress-bar.xyz/${{ steps.kover-branch-values.outputs.percent }}) |
            | Line | ${{ steps.kover-line-values.outputs.covered }} | ${{ steps.kover-line-values.outputs.missed }} | ![](https://progress-bar.xyz/${{ steps.kover-line-values.outputs.percent }}) |
            | Method | ${{ steps.kover-method-values.outputs.covered }} | ${{ steps.kover-method-values.outputs.missed }} | ![](https://progress-bar.xyz/${{ steps.kover-method-values.outputs.percent }}) |
            | Class | ${{ steps.kover-class-values.outputs.covered }} | ${{ steps.kover-class-values.outputs.missed }} | ![](https://progress-bar.xyz/${{ steps.kover-class-values.outputs.percent }}) |
