name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Up
        uses: ./.github/actions/setup

      - name: Extract google-services.json
        run: |
          cat << EOF > ./composeApp/google-services.json
          ${{ secrets.GOOGLE_SERVICES }}
          EOF

      - name: Build with Gradle
        run: ./gradlew :composeApp:assembleDebug

  tests:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Up
        uses: ./.github/actions/setup

      - name: Run unit tests
        run: ./gradlew clean test

  ktlint:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Up
        uses: ./.github/actions/setup

      - name: Run ktlint
        run: ./gradlew --continue clean ktlintCheck

  kover:
    needs: [tests, ktlint]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set Up
        uses: ./.github/actions/setup

      - name: Extract google-services.json
        run: |
          cat << EOF > ./composeApp/google-services.json
          ${{ secrets.GOOGLE_SERVICES }}
          EOF

      - name: Run kover
        run: ./gradlew clean composeApp:koverHtmlReportDebug
