name: Kover report parser
description: Parse value from kover report

inputs:
  path:
    description: "Report path"
    required: true
  type:
    description: "Type of value to parse"
    required: true

outputs:
  covered:
    description: "Covered value"
    value: ${{ steps.covered_value.outputs.covered }}
  missed:
    description: "Missed value"
    value: ${{ steps.missed_value.outputs.missed }}
  percent:
    description: "Percent of covered over all"
    value: ${{ steps.percent_value.outputs.percent }}

runs:
  using: composite
  steps:
    - name: Parse covered
      id: covered_value
      run: |
        covered=$(xmllint --xpath "string(report/counter[@type='${{ inputs.type }}']/@covered)" ${{ inputs.path }})
        echo "covered=$covered" >> $GITHUB_OUTPUT
        echo "COVERED=$covered" >> $GITHUB_ENV
      shell: bash

    - name: Parse missed
      id: missed_value
      run: |
        missed=$(xmllint --xpath "string(report/counter[@type='${{ inputs.type }}']/@missed)" ${{ inputs.path }})
        echo "missed=$missed" >> $GITHUB_OUTPUT
        echo "MISSED=$missed" >> $GITHUB_ENV
      shell: bash

    - name: Calculate total
      id: total_value
      run: |
        total=$((${{ env.COVERED }}+${{ env.MISSED }}))
        echo "total=$total" >> $GITHUB_ENV
      shell: bash

    - name: Calculate percent
      id: percent_value
      run: |
        percent=$(awk 'BEGIN {print (${{ env.COVERED }}/${{ env.total }}*100)}')
        echo "percent=$percent" >> $GITHUB_OUTPUT
      shell: bash